### ISSUE TITLE
Build keretrendszer + CI beüzemelése (GitHub Actions)

### ISSUE THREAD

**Issue by AdamPongor** [BME-MIT-IET/iet-hf-2023-monkesoft-2-electric-boogaloo#1]
Gradle beüzemelése a repositoryra. Rumi Zoárd dolgozik rajta.

**Comment by AdamPongor** [comment]
Sikertelen Maven Build branch: #2 (lezárva és elutasítva)
@rumizz -zal úgy döntöttünk, inkább Gradle-t használunk.

**Comment by rumizz** [comment]
Gradle build branch: #3

**Comment by AdamPongor** [comment]
Feljebb azért zárult le az issue, mert linkeltem egy pull requesthez, mert nem tudtam, hogy az automatikusan lezárja.

Ugyanitt egy kicsit lemaradtunk a requestek linkelgetésével, tehát:
- Kiderült, hogy a gradle build nem a projektfájlokra fut le, csak egy példa osztályra. Ezt a hibát @rumizz javította: #8 
- A BDD tesztekhez kicsit át kellett alakítani a build.gradle formátumát. Ezt @Xeldas végezte: #10

**Comment by AdamPongor** [comment]
Kiegészítés a dokumentációba: #30

**Comment by Xeldas** [comment]
@AdamPongor és @rumizz munkáját én ellenőriztem, az én munkámat pedig @AdamPongor.
