### ISSUE TITLE
Manuális kód átvizsgálás + Statikus analízis eszköz futtatása

### ISSUE THREAD

**Issue by AdamPongor** [BME-MIT-IET/iet-hf-2023-monkesoft-2-electric-boogaloo#4]
SonarLint és SonarCloud futtatása a projekten, majd jelzett hibák javítása. Pongor Ádám fog rajta dolgozni.

**Comment by AdamPongor** [comment]
A SonarLint által jelzett jelentős hibákat javítottam a projektben: #6

**Comment by AdamPongor** [comment]
SonarCloud beállítva a repositoryra: #19

**Comment by AdamPongor** [comment]
SonarCloud által jelzett hibák nagy része javítva: #20

**Comment by AdamPongor** [comment]
SonarCloud dokumentáció: #22

**Comment by AdamPongor** [comment]
Összegzés: #27

**Comment by rumizz** [comment]
A PR-okat ellenőriztem és végül mindet elfogadtam. A feladatot befejezettnek tekinthetjük, ezért az issue-t lezárom.
