### ISSUE TITLE
Code smell: type casting

### ISSUE THREAD

**Issue by rumizz** [BME-MIT-IET/iet-hf-2023-monkesoft-2-electric-boogaloo#5]
JEffect:38
`Individual unused_variable_lmao = (Individual) effect.GetEffect();`
A szerző szándéka valószínület az volt, hogy a castolással checkolja, hogy az effect a megfelelő leszármazott osztály példánya-e. Nem konvencionális, és instanceof kérést megkerülő módszer.

**Comment by AdamPongor** [comment]
Módosítottam visitor patternre: #6
