### ISSUE TITLE
BDD tesztek készítése

### ISSUE THREAD

**Issue by AdamPongor** [BME-MIT-IET/iet-hf-2023-monkesoft-2-electric-boogaloo#7]
BDD tesztek írása Cucumberrel. Sipos Krisztián vállalta el.

**Comment by Xeldas** [comment]
build.gradle módosítva, Cucumber hozzáadva a projekthez. #10

**Comment by Xeldas** [comment]
Package struktúra módosítva, néhány teszt elkészítve. #14

**Comment by Xeldas** [comment]
IDE által elrontott UI stringek kijavítása, build.gradle mainclass módosítás a package struktúrának megfelelően. #15

**Comment by Xeldas** [comment]
Komplex tesztek készítése. #24

**Comment by Xeldas** [comment]
Dokumentáció feltöltése. #24

**Comment by rumizz** [comment]
Remek munka. Issue lezárva.

**Comment by Xeldas** [comment]
Utolsó kiegészítések a dokumentációban. #29

**Comment by AdamPongor** [comment]
A dokumentáció kiegészítéseket átnéztem. Szép lett, issue lezárható
