### ISSUE TITLE
Manuális / felderítő tesztelés

### ISSUE THREAD

**Issue by AdamPongor** [BME-MIT-IET/iet-hf-2023-monkesoft-2-electric-boogaloo#9]
A szoftver manuális tesztelése felhasználói felületen keresztül. Nagy Tamás vállalta el, mivel neki új a projekt.

**Comment by Xeno98** [comment]
#12 Tesztelve dokumentálva

**Comment by AdamPongor** [comment]
Az alábbi pull requestekben találhatóak a jelentősebb bugok javításai, amiket a manuális tesztelés tárt fel:
Játékosszám limitálása: #17 
Halott virológus továbbra is játékban marad #18 
Inventory increase helytelen megszűnése: #21

**Comment by Xeldas** [comment]
Manuális tesztek újrafuttatása, problémák javítottságának újraértékelése @Xeno98 által. #23

**Comment by Xeldas** [comment]
Maradék táskával való hiba javítása. #25

**Comment by rumizz** [comment]
Összegzés. #26

**Comment by rumizz** [comment]
A manuális tesztek dokumentációs és javítási PR-jait ellenőrizte: @AdamPongor @rumizz @Xeldas. A feladatot befejezettnek tekintjük.
